In [2]:
import numpy as np

In [3]:
a=np.array([[2,3],[4,5]])
print(a)
b=np.array([[4,5],[7,8]])
print(b)

[[2 3]
 [4 5]]
[[4 5]
 [7 8]]


In [6]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[ 6  8]
 [11 13]]
[[-2 -2]
 [-3 -3]]
[[ 8 15]
 [28 40]]
