In [1]:
import numpy as np

Creating A matrix using numpy

In [3]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_1.transpose()

array([[2, 6],
       [3, 7]])

In [6]:
matrix_2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix_2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
matrix_2.shape

(3, 3)

Creating matrix with random variables


In [20]:
matrix_4=np.random.rand(3,3)
print(matrix_4)

[[0.62536501 0.29400507 0.87363042]
 [0.92916033 0.36731269 0.1938471 ]
 [0.96542046 0.05159105 0.61096329]]


In [19]:
matrix_3=np.random.randint(0,10,size=(3,3))
print(matrix_3)

[[3 6 7]
 [9 9 3]
 [9 6 9]]


In [21]:
matrix_5=np.full((3,3),1)
print(matrix_5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
matrix_06=np.ones((3,3))
print(matrix_06)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
matrix_7=np.eye(3,3)
print(matrix_7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
